name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to push back to main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Set git commit in version.py
        shell: pwsh
        run: |
          $git_commit = git rev-parse --short HEAD
          (Get-Content version.py) -replace '__git_commit__ = ".*"', "__git_commit__ = `"$git_commit`"" | Set-Content version.py
      - name: Build executable
        run: |
          pyinstaller --onefile --name chrome.exe --version-file version_info.txt chrome.py
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/chrome.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit updated version.py back to main
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add version.py
          git commit -m 'chore: update version.py with release commit hash [skip ci]' || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
